# A git hub actions workflow to run pdk validate and pdk test unit
# on puppet modules

name: puppet-pdk

on: push

permissions:
  contents: read

jobs:
  pdk-validate:
    name: Run pdk validate
    runs-on: ubuntu-latest
    container: 
      image: puppet/puppet-dev-tools:puppet8

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: pdk-validate
        run: pdk validate --format=text:output.out

      - name: show pdk vallidate errors
        if: failure()
        run: cat output.out

      - name: pdk-test-unit
        if: success()
        run: pdk test unit
